server:
  port: 8888

spring:
  cloud:
    config:
      server:
        svn:
          uri: https://172.16.1.30/svn/iCashPro_Product/branches/SBI
          default-label: trunk
          username: mayurm.patil@aurionpro.com
          password: Rabale@123
          basedir: F:/SVN
          search-paths:
            - /Commons/config/**

  application:
    name: SPRING_CONFIG_SERVER

  profiles:
    active: subversion

logging:
  level:
    root: INFO
    org.springframework.boot.env.PropertySourcesLoader: INFO
    org.springframework.cloud.config.server: INFO