server:
  port: 8888

spring:
  cloud:
    config:
      server:
        svn:
          uri: svn branch url
          default-label: trunk
          username: email
          password: eamil password
          basedir: F:/SVN
          search-paths:
            - /Commons/config/**

  application:
    name: SPRING_CONFIG_SERVER

  profiles:
    active: subversion

logging:
  level:
    root: INFO
    org.springframework.boot.env.PropertySourcesLoader: INFO
    org.springframework.cloud.config.server: INFO